### ISSUE TITLE
Zooming on portable devices

### ISSUE THREAD

**Issue by Khegyi** [nicolas-t/Chocolat#10]
Hi!

I don't know if this is an issue or just an incomplete function, but when i tap the image on an android tablet, with chrome browser, it seem it gets zoomed in where i tapped the image, but after that i can't move around, i can only unzoom. 

Thanks.

**Comment by nicolas-t** [comment]
Hi Khegyi,

It's more of an incomplete feature...
What would you expect on touch devices ?

Nicolas,

**Comment by Khegyi** [comment]
Hi Nicolas,

It would be great if i could move around the picture after i zoom in. 

Thanks!

**Comment by nicolas-t** [comment]
Thank you for your feadback, it'll be part of the next major release of a more touch friendly chocolat :)
