### ISSUE TITLE
No mobile support

### ISSUE THREAD

**Issue by mcasieri** [nicolas-t/Chocolat#119]
Hi, this plugin works great in responsive environment but it totally lacks of mobile support.

For example, a covered or full screen image that overflow screen margin can't be dragged, scrolled, zoomed.
Does anyone tried to do something similar to mobile?

Thanks to all

**Comment by nicolas-t** [comment]
Hello,

You are right it misses mobile support.
It has been discussed here already:
https://github.com/nicolas-t/Chocolat/issues/25
https://github.com/nicolas-t/Chocolat/issues/68

Feel free to re-open if needed.
