### ISSUE TITLE
Images flash/stutter when navigating

### ISSUE THREAD

**Issue by interactivematt** [nicolas-t/Chocolat#12]
I love this plugin. The only issue I've noticed so far is that if there are a two images at different sizes next to each other, the transition between them hiccups quite a bit. It would be awesome if this could be solved. I can post a screencast if necessary. Thanks!

**Comment by nicolas-t** [comment]
Thanks for your feedback, I dont notice any glitches on the transition, so... yep, a screencast would be greatly appreciated. Any informations about browser, OS, images size (ko),... are also welcome.

thanks,
