### ISSUE TITLE
feature_request(enhancement): thumbnails bar

### ISSUE THREAD

**Issue by Kristinita** [nicolas-t/Chocolat#121]
### 1. Summary

It would be nice, if Chocolat as its alternatives will have thumbnails bar.

#### 2.1. Common cause

Accessibility. Save users time.

#### 2.2. Details

Currently, Chocolat end-user can solely view one image after another. If the gallery of images is large, it can be time-consuming.

If thumbnails bar will implement, end-users can quickly view all gallery.

#### 3.1. Fancybox (preferable)

Right-side bar.

[**Demo**](https://fancyapps.com/fancybox/3/):

![Fancybox](https://i.imgur.com/4QODeYN.png)

#### 3.2. lightGallery.js

[**Demo**](https://sachinchoolur.github.io/lightgallery.js/demos/index.html#lg=1&slide=19):

![lightGallery.js](https://i.imgur.com/4Qw0ws7.png)

### 4. Note

If this feature will be implemented, it would be nice to make it as a separated plugin, as in [**lightgallery.js**](https://sachinchoolur.github.io/lightgallery.js/demos/index.html#lg=1&slide=19), e.g.:

```html
<script src="https://cdn.jsdelivr.net/npm/chocolat/dist/js/chocolat.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/chocolat/dist/js/plugins/chocolat-thumbnail.min.js" defer></script>
```

In order to reduce the JavaScript size for users who don’t need this feature.

Thanks.

**Comment by nicolas-t** [comment]
Hello,

I want to keep Chocolat very simple and low level, so I won't implement it directly in the project.
But you are right, it can be built as an external plugin, once again it should be easy using Chocolat's API.
