### ISSUE TITLE
Firebug: Uncaught SyntaxError

### ISSUE THREAD

**Issue by dietantejensen** [nicolas-t/Chocolat#124]
Hi, I'm running in 2 errors:

Uncaught SyntaxError: import declarations may only appear at top level of a module chocolat.js:1
Uncaught ReferenceError: Chocolat is not defined
    <anonymous> http://...../javascript/general.js?1613495647:27

HTML:
  <script src="...../javascript/Chocolat-1.0.0/src/js/chocolat.js?1586337866" type="text/javascript"></script>
  <script src="...../javascript/cookieconsent.en.js?1611224951" type="text/javascript"></script>
</body>

I thought you'd might like to know.
Cheers, Nils

**Comment by nicolas-t** [comment]
Hello,

You should use the files in the ./dist/ folder, not in the ./src/ folder.

Nicolas,
