### ISSUE TITLE
Fullscreen close does not work in safari

### ISSUE THREAD

**Issue by josh-attwood** [nicolas-t/Chocolat#125]
I'm having an issue with fullscreen not closing properly in safari. Seems absolutely fine in other browsers. When you click close or trigger a close through the API it leaves you with a black container and you can only escape using 'esc' on the keyboard.

**Comment by nicolas-t** [comment]
Thanks,

Unfortunately I don't have access to a safari browser for the moment.

**Comment by nicolas-t** [comment]
Ok it should be fixed.
Can you try with this version ? https://github.com/nicolas-t/Chocolat/releases/tag/1.0.4

Feel free to reopen if the bug persists

**Comment by josh-attwood** [comment]
That seems to have done the job. Thanks!
