### ISSUE TITLE
Container contain example demo page

### ISSUE THREAD

**Issue by cassianotartari** [nicolas-t/Chocolat#13]
Hello!

I'm playing with the library and trying to reproduce the same example as in homepage when we have an starting picture inside container with contain imageSize and no close button. What is the best practice to hide the chocolat-top bar with close button inside?

**Comment by nicolas-t** [comment]
Hi!
  
All of these modifications have to be done in the `css/chocolat.css` file.

you can add : 
```
height: 0;
display: none;
```
to the selector:  
`.chocolat-wrapper .chocolat-top`

But as chocolat keeps the image centered it may overlap the `.chocolat-bottom` element

----

So this is what I did on the website:  
I didn't hide the `chocolat-top` nor the `chocolat-bottom` element, I just put the pagination in the `chocolat-top` and  added `display: none;` to `.chocolat-close` and  `chocolat-fullscreen` (to hide them)
  
  
Hope this helps, if not, don't hesitate.

**Comment by cassianotartari** [comment]
many thanks @nicolas-t but I was looking for a quickly solution and I chose Owl Carousel http://owlgraphic.com/owlcarousel/

I will keep an eye on Chocolat ;)
