### ISSUE TITLE
Chocolat not working with IE11

### ISSUE THREAD

**Issue by PhucNguyen1501** [nicolas-t/Chocolat#130]
Hey,

I've been using Chocolat and enjoying it so far. Recently I encountered an issue with IE11 throwing a syntax error in the chocolat.js: Line 13, Column 35 as shown below:

<img width="859" alt="Screen Shot 2021-10-15 at 3 25 32 pm" src="https://user-images.githubusercontent.com/62129450/137434466-be72cd49-6481-438d-83a5-9d9c328e553d.png">

I believe this is because IE11 does not support direct arrow function (as per ES6). Can you investigate this?

Cheers

**Comment by nicolas-t** [comment]
Hello,

I don't have access to IE11.
Can you try installing `chocolat@1.0.5-beta.0` ?

If you use the classic import described [here ](https://chocolat.gitbook.io/chocolat/#classic-import) be sure to use the js files in the `./dist` directory (and not `./src`)

Thanks for your help

**Comment by nicolas-t** [comment]
Closing. 
Feel free to reopen if you need any help.

**Comment by PhucNguyen1501** [comment]
> Hello,
> 
> I added polyfills and now it should work on IE11 with this release: `1.0.5-beta.2`

Hi Nicolas,

It works fine with IE11 now. Thanks for your help thus far.

Cheers!
