### ISSUE TITLE
Make a version angularjs

### ISSUE THREAD

**Issue by jonyw4** [nicolas-t/Chocolat#14]
I loved the concept of this lightbox, but it is only in jquery. You do not have in mind to do a version for angularjs? I can help

**Comment by nicolas-t** [comment]
Hi,

(even a version for angularjs would require jQuery) 
I don't have plans to make an angular directive out of chocolat.js, (i don't really like angularjs) but I think it's not that much work.

By the way I've asked a friend if he's interested in making it, I'll keep you updated.

**Comment by beuted** [comment]
:+1:

**Comment by beuted** [comment]
Hey I've done an angular version of chocolat in a very simple directive, you can [find it here](https://github.com/beuted/ng-chocolat/blob/master/README.md). Cheers!
