### ISSUE TITLE
Trying to open lightbox upon click

### ISSUE THREAD

**Issue by josleow** [nicolas-t/Chocolat#15]
Came across your chocolat and gave it a try. 

I am adding it in Drupal as a plugin and I tried to have a class per thumbnail so it would open lightbox with images (on node page) as similar to your demo. But when tried to click thumbnail, it only shows the full node page, not lightbox. 

Is there something else that I might be overlooking?

Example:
`<a href="node/12" class="thumbnail"><img src="/path/to/image.png"/></a>`

jQuery(document).ready(function($){
  $('.thumbnail').Chocolat({
    container: window,
    fullWindow: 'contain',
    fullScreen: false,
    loop: true,
    duration: 300,
  });
});

**Comment by nicolas-t** [comment]
Yep,

try 
```
$(document).ready(function(){
    $('body').Chocolat({
          imageSelector : '.thumbnail'
     });
});
```

**Comment by josleow** [comment]
@nicolas-t - thank you so much for the quick reply. 

Lightbox appears, but there is no images and text. Is it possible to take url i.e. node/12  to display images and text? Or I have to follow the doc to add class "chocolat-image" to images?

Thanks

**Comment by nicolas-t** [comment]
Hi,

What does `node/12` looks like ? 
If you want something more flexible you can pass images as a json object : 

```
$(document).ready(function(){
    $('body').Chocolat({
         images : [{src:'img1.jpg', title: 'title1'}, {src:'img2.jpg', title: 'title2'}, ..]
     });
});
```

But it's not easy to help you without seeing your complete markup (html) and javascript

**Comment by josleow** [comment]
node/12 is a page with images and body text to explain. For example,
fancybox can accept url in ajax process to show the page on fancybox (
http://fancyapps.com/fancybox/)

I am helping my friend to set up the portfolio - so can only send you PM -
can I pm you the url for a look?

Thanks

Thank you,
Josephine

**Comment by nicolas-t** [comment]
Yep email me `nicolas at insipi.de` 
But you can't load iframe/videos/ajax content with chocolat.

**Comment by NipSauce** [comment]
I seem to have the same problem unfortunately. Whenever i click the working thumbnail links, I get forwarded to the images URL instead of the lightbox picking up the call.

My defaults look like this right now:
```javascript
var defaults = {
        container         : '#container2',
        imageSelector     : '.chocolat-image',
        className         : '',
        imageSize         : 'contain',
```
And my html:
```html
<div id="lightbox">
	<a class="chocolat-image" href="demo-images/5.jpg" title="HO">
	    <img src="demo-images/5.jpg" alt="1" width="96" height="54">
	</a>
	<a class="chocolat-image" href="demo-images/6.jpg" title="HAI">
	    <img src="demo-images/6.jpg" alt="1" width="96" height="54">
	</a>
	<a class="chocolat-image" href="demo-images/3.jpg" title="IO">
	    <img src="demo-images/3.jpg" alt="1" width="96" height="54">
	</a>
 </div>
 <div id="container2" style="width: 80%; max-width:1000px; height: 600px;background: #E0E0E0;margin:auto;"></div>
```

Do you see anything out of the ordinary here?
Is fullpage.js maybe interfering?

Using jQuery v1.8.3

**Comment by nicolas-t** [comment]
@NipSauce Hi, please open a new issue, and provide a demo with the failing code.Thanks,

@josleow I've answered your email.
