### ISSUE TITLE
Example of handling Parameters

### ISSUE THREAD

**Issue by johnnywon** [nicolas-t/Chocolat#18]
Can you provide an example of how to handle the Parameters? I've tried variations of this and have failed: 

$(document).ready(function(){
    $('#example1').Chocolat(
	     duration : 1200,
	     imageSize : 'native'
    );
});

Thank you, great plugin.

**Comment by nicolas-t** [comment]
Hi,

You can find a lot of examples in the file `dist/index.html`

In the code you provide the curly brackets are missing

```
$(document).ready(function(){
	$('#example1').Chocolat({
		duration : 1200,
		imageSize : 'native'
	});
});
```

You can learn more about literal objects here 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Object_literals

**Comment by johnnywon** [comment]
Thank you! You should update the readme with this example to make this simpler to understand.
