### ISSUE TITLE
default image, move title banner

### ISSUE THREAD

**Issue by mvdepot** [nicolas-t/Chocolat#19]
Howdy, thank you for the Chocolat.

How would it be best to require Chocolat to show a starting image when using a container (DIV)?
Would like to have it show the first image in the set when the document loads.

Also, how can one easily move the title banner to the top of the images instead of bottom in chocolat.css? 

Merci!

**Comment by mvdepot** [comment]
I did find a solution for these two queries, perhaps not the best but it works great for my application.
to preload the first image on the page I am using this to call Chocolat:
```javascript  
<SCRIPT>
    var inContainer = $('.chocolat-parent').Chocolat({
        imageSize : 'native',
		loop: true,
        container      : '#full_bin'
    }).data('api-chocolat');
	
	$(document).ready($(".chocolat-image")[0].click());
</SCRIPT>
```
to move the banner that displays on the image I just swapped  some of the elements in the 
  **markup:function()** from bottom to top - seems to work well.

One change I might suggest to Chocolat, if I may. When you have **loop : true** set the arrows 
show on the sides, even if there is only one image in the set. I asked Chocolat to make sure there is
more than one image before adding arrows at line 247:
```javascript  
  arrows: function() {
    if (this.settings.loop & this.settings.lastImage > 0) {
```
Thank you again for the nifty script.

**Comment by nicolas-t** [comment]
Salut!

Thanks for asking and congrats on modifiying the code to your needs, thats how chocolat is supposed to be used.

The best way to open the first image is to use the API like this :  
```
`<SCRIPT>
    $(document).ready( function() {
        var inContainer = $('.chocolat-parent').Chocolat({
            imageSize : 'native',
            loop      : true,
            container : '#full_bin'
        }).data('chocolat');

        inContainer.api().open()
    });
</SCRIPT>

For the markup functino and the loop arrows, your code is right :)
```
