### ISSUE TITLE
Non-JQuery Version & Non-Image elements

### ISSUE THREAD

**Issue by oyeanuj** [nicolas-t/Chocolat#22]
Hi @nicolas-t! Great work on the polish of the plugin!

I was wondering if you plan to support the following anytime soon - 

1. Non- JQuery version: I am coming from the land of React and unfortunately, React and JQuery aren't the best of friends. Any possibility of stripping out the JQuery dependency anytime?

2. Non-image elements: It seems like this pattern (container/cover/etc) would be useful for showing articles, videos etc. Is it possible today or would be easy to allow this plugin to support any HTML element as an input, not just images?

Thanks so much!

**Comment by nicolas-t** [comment]
Hi !
Yes! I want to make chocolat jquery-free, I don't know when, maybe it'll come with an ES6 (or coffeescript ?) rewriting. In the coming months

whereas non-image elements are not planned.
