### ISSUE TITLE
The `main` field in the `package.json` has to be a string

### ISSUE THREAD

**Issue by jackmu95** [nicolas-t/Chocolat#27]
When you try installing Chocolat via npm you get this error:
```bash
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Path must be a string. Received [ 'css/chocolat.css', 'js/jquery.chocolat.js' ]
```

The [npm documentation](https://docs.npmjs.com/files/package.json#main) for the `main` field says:
> The main field is a module ID that is the primary entry point to your program.

**The value should be changed to `js/jquery.chocolat.js`.**

**Comment by nicolas-t** [comment]
Thanks a lot. I fixed it on master.

**Comment by nicolas-t** [comment]
By the way, you can't install chocolat with npm
