### ISSUE TITLE
FullScreen

### ISSUE THREAD

**Issue by jpl12** [nicolas-t/Chocolat#29]
Great plugin!!.
In the dist folder on chocolat-0.4.10.zip to run the index.html, pressing on the button fullscreen on any of the containers, the maximized image is not centered. As I do?
Thank you.

**Comment by nicolas-t** [comment]
Fixed in 0.4.11
https://github.com/nicolas-t/Chocolat/releases/tag/0.4.11

Thanks again for reporting
