### ISSUE TITLE
parameters for zoom etc

### ISSUE THREAD

**Issue by benbyford** [nicolas-t/Chocolat#30]
Hello.

Think more parameters could be added for use of zoom or not, nav, etc...

**Comment by nicolas-t** [comment]
Hi

Not sure to understand your point

Parameters to enable zoom or not ? to enable navigation or not ?

**Comment by benbyford** [comment]
indeed. i.e. i dont want to use the zoom feature but am unable to turn it off in teh param's without editing the vendor code directly

**Comment by nicolas-t** [comment]
Thanks for your PR !
