### ISSUE TITLE
Missing *-compact.png images

### ISSUE THREAD

**Issue by ptrckvzn** [nicolas-t/Chocolat#32]
Hello, 
first, thanks for this great plugin!

I am using npm to install Chocolat and webpack to build my assets and I get an error of missing images from the images folder when I "compile" the css. Those files seems to be missing from the images folder: left-compact.png, right-compact.png, close-compact.png. I am wondering if those lines shouldn't be removed?

https://github.com/nicolas-t/Chocolat/blob/master/src/css/chocolat.css#L161

https://github.com/nicolas-t/Chocolat/blob/master/src/css/chocolat.css#L165

https://github.com/nicolas-t/Chocolat/blob/master/src/css/chocolat.css#L174

**Comment by nicolas-t** [comment]
Hi Patrick ! 
I love you avatar so much, reminds me I should bring my pineapple with me more often!

About chocolat :  
compact mode doesn't exists anymore.
You can safely remove all these lines :  
https://github.com/nicolas-t/Chocolat/blob/master/src/css/chocolat.css#L151L187
(pull request is welcome, if you don't have the time i'll do it in the coming days)

If you don't want to edit the css you can find the missing images here:  
https://github.com/nicolas-t/Chocolat/tree/295a678829d53587f092c9a5633be0e4552c55a1/images

:pineapple:

**Comment by ptrckvzn** [comment]
Ok I'll do a pull request later today!

My avatar is actually a still from the awesome movie Life is Sweet by Mike Leigh ;) https://www.youtube.com/watch?v=UYPoTS2Ruv0

**Comment by nicolas-t** [comment]
thanks buddy
