### ISSUE TITLE
Image caption used somewhere?

### ISSUE THREAD

**Issue by ibrambe** [nicolas-t/Chocolat#36]
In your example you add an explicit caption in the title attribute: 

`<a class="chocolat-image" href="img/a.jpg" title="image caption a">`

Is it possible to display it as a caption somewhere or it is just nothing :)

**Comment by nicolas-t** [comment]
Hi,

Yes it's displayed in the element `.chocolat-description` by default at the bottom left of the lightbox.

"yellow" here, for example:
![capture](https://cloud.githubusercontent.com/assets/1765930/14667707/dce659c8-06e0-11e6-8b49-4c200090c09f.PNG)

**Comment by ibrambe** [comment]
Okay, that's clear. The element `.chocolat-description` was hidden in my setup, css mistake of mine. Thanks for your fast reply.
