### ISSUE TITLE
About npm version

### ISSUE THREAD

**Issue by x09326** [nicolas-t/Chocolat#37]
Hi, I'm going to host this project on [cdnjs](https://cdnjs.com).
Can you update this project in npm?
Because I saw the version of this project in npm is still 0.4.12

Thank you for your help.

**Comment by nicolas-t** [comment]
Hi,
I'm new to NPM, do you know why it doesn't use the last release (0.4.13) ?

Anyway i'll take a deeper look on friday or during the weekend.

Best regards,

**Comment by PeterDaveHello** [comment]
hmmm ... npm says it was published a month ago, maybe forgot to publish the new version?

**Comment by PeterDaveHello** [comment]
and seems there are only two releases on npm but 14 releases on GitHub.

**Comment by x09326** [comment]
Okay, I will use git auto-update.
And I want to know whether the ```demo-images``` in the ```dist``` should be included.

**Comment by PeterDaveHello** [comment]
I guess not :smile:
