### ISSUE TITLE
suggestion: make the markup functioncustomizable

### ISSUE THREAD

**Issue by horacegrant** [nicolas-t/Chocolat#39]
chocolat is really great! :)

but i would have two suggestions:

.chocolat-bottom should use some user customizable template. i find the behaviour of the floated elements really weird in a responsive website. of course the css can be changed but non-floated the order is wrong and this only can be fixed by changing the script.

and other lightbox scripts offer various useful callbacks. like after the lightbox got constructed, after a new image gets displayed,... and such things. that would be very useful too!

**Comment by nicolas-t** [comment]
Hi!

It would be realy cool to use a custom [markup function](https://github.com/nicolas-t/Chocolat/blob/master/dist/js/jquery.chocolat.js#L354)  i've already thought of it, but i haven't find the best way to implement it yet.

If you have any suggestions, don't hesitate.

You can create a pull request aswell :)

**Comment by horacegrant** [comment]
i think i would do it with some kind of formatting string.

`bottomHTML: '<div>%%title%%</div><div>%%pagination%%</div>'`

and there are some predefined variables that can be inserted.

maybe if i find some time i will try to do it myself and learn git and send you pull request. :)

**Comment by nicolas-t** [comment]
Hi @horacegrant i've just released a new version implementing a hook you can use to manipulate the layout.  
see https://github.com/nicolas-t/Chocolat/releases/tag/0.4.14

**Comment by horacegrant** [comment]
awesome! thanks! :)
