### ISSUE TITLE
Image Caption

### ISSUE THREAD

**Issue by gwarmy** [nicolas-t/Chocolat#42]
Hi Nicolas, it´s possible to display the "chocolat-description" in the "chocolat-top" section? Thanks.

**Comment by nicolas-t** [comment]
Hi!

One solution (not ideal) is to edit this line : 
https://github.com/nicolas-t/Chocolat/blob/master/dist/js/jquery.chocolat.js#L408

like this: 
```javascript
// before
this.elems.description = $('<span/>', {
    'class' : 'chocolat-description'
}).appendTo(this.elems.bottom);
```
```javascript
// after
this.elems.description = $('<span/>', {
    'class' : 'chocolat-description'
}).appendTo(this.elems.top);
```
(maybe you'll have to do some css adjustments too)

I'm aware that modifying the vendor (chocolat) is not ideal, and i've planned to make the markup fonction customizable in a near future, more informations here: https://github.com/nicolas-t/Chocolat/issues/39

Best regards,

**Comment by gwarmy** [comment]
Thanks! I'll try it. Best

**Comment by nicolas-t** [comment]
Hi @gwarmy i've just released a new version for this usecase, see https://github.com/nicolas-t/Chocolat/releases/tag/0.4.14
