### ISSUE TITLE
Overlay allows for scrolling div below

### ISSUE THREAD

**Issue by afonsogonsalves** [nicolas-t/Chocolat#45]
Hey Nicolas, it's me again. :)

http://afonsogonsalves.com/skannwas/
On this page, when you open the chocolat "slideshow", the thumbnails on the div below move when you scroll. Is there a way to stop this from happening, locking the scroll somehow?

Thanks!! 👍

**Comment by nicolas-t** [comment]
By defautl you can't scroll when chocolat is open.
In your case you're css is forcing the scrollbar.

try removing the `overflow-y: scroll;` from your `html` element, and it should be ok.

Nicolas,

**Comment by afonsogonsalves** [comment]
Ah, I see — indeed that stops the scrolling.
However, without `overflow-y: scroll;` the page jumps when closing chocolat, since the page below needs to scroll...

**Comment by nicolas-t** [comment]
in that case just add this in your css 
```css
.bg.chocolat-open {
    height: 100%;
}
```

**Comment by nicolas-t** [comment]
another solution could be to close chocolat when the user scrolls: 

```javascript
var chocolat = $('#chocolat').Chocolat().data('chocolat');
$(document).on('scroll', function () {
    if (chocolat.api().current() !== false) {
        chocolat.api().close()
    }
})
```
(i haven't tested it live)
