### ISSUE TITLE
Add afterLoad hook

### ISSUE THREAD

**Issue by slavanga** [nicolas-t/Chocolat#47]
An afterLoad hook similar to the afterMarkup hook would be useful to trigger things after Chocolat is opened and initialized.

**Comment by nicolas-t** [comment]
Hum yes. Why not. 
Do you mind telling me what is your use case ?
Thanks

**Comment by slavanga** [comment]
My original use case was to activate zoom mode after Chocolat is opened. But I thought a general afterLoad hook would be beneficial for more people.

**Comment by nicolas-t** [comment]
Ok,

You can use the API and its deferred objects for this:
```javascript
var chocolat = $('.container').Chocolat()
var api = chocolat.api()
api.open().done(function(){
    console.log('open done');
    api.getElem['img'].trigger('click.chocolat')
})
```

But to zoom you'll have to trigger a click on the `img` which is not very elegant, so I'll add `zoomIn` and `zoomOut` methods to the API in the coming days.

**Comment by nicolas-t** [comment]
or myabe i can use the property `initialZoomState`, mhhh

**Comment by xmon** [comment]
Hi @nicolas-t 

I need to get src attribute from img opened, but I can't.

My purpose is to generate a URL to mount the Twitter URL intent. With this proposed feature, I think I could do it without problems.

Any progress with this issue?

thanks a lot

**Comment by nicolas-t** [comment]
Hi,

You need a hook that get called once an image is loaded ? 
I'm adding both hooks (once the lightbox opens and once the image changes)

Will deploy in a few hours.

Best regards,

**Comment by nicolas-t** [comment]
there you go : https://github.com/nicolas-t/Chocolat/releases/tag/0.4.15
Reopen if you have any question.
