### ISSUE TITLE
'Fitting not defined' error

### ISSUE THREAD

**Issue by dlewand691** [nicolas-t/Chocolat#49]
Running a Mac with Codekit. With minification on and trying to zoom, getting this error:

```
Uncaught ReferenceError: fitting is not defined
zoomIn @ jquery.chocolat.min.js:1(anonymous function) 
@ jquery.chocolat.min.js:1dispatch 
@ jquery.js:4737m.handle 
@ jquery.js:4549
```

<img width="671" alt="screen shot 2016-08-05 at 1 30 10 pm" src="https://cloud.githubusercontent.com/assets/1159913/17444978/c86cc994-5b10-11e6-86f3-f12a4aebfa4f.png">

Works fine if I don't minify, but obviously need to minify.

**Comment by trajedy** [comment]
I'm also getting the same error

**Comment by nicolas-t** [comment]
Hi !

Thanks for your feedback, I'm not sure to understand, do you use the minified version of chocolat (dist/js/jquery.chocolat.min.js) ?
or do you use codekit to minify it ? 

I can't reproduce the error, so an online demo with steps to reproduce would be useful.

thanks

**Comment by nicolasbinet** [comment]
Hi,
I got the same error, second time today using an external library and concatening & uglifying with laravel elixir. Adding a "var fitting " line 564, 603 & 618 made my day.
Using the lib alone won't raise the same problem.
Hope this helps.
Nicolas

**Comment by nicolas-t** [comment]
Great ! indeed some `var` are missing.
can you make a pull request?

merci

**Comment by nicolas-t** [comment]
closed https://github.com/nicolas-t/Chocolat/releases/tag/0.4.15
