### ISSUE TITLE
Include SASS/SCSS file with distribution

### ISSUE THREAD

**Issue by dlewand691** [nicolas-t/Chocolat#53]
Would love to have a .scss file included so I can import into my projects. Currently I copy the .css file out and change the extension to .scss. Having the .scss included in the distribution ensures that I'm using the latest version.

Thanks!

**Comment by nicolas-t** [comment]
Yep, 
But for the sake of simplicity this project doesn't use a css preprocessor.
you can still use `@import` on the .css file, don't you?
