### ISSUE TITLE
New instance of chocolat wrapper

### ISSUE THREAD

**Issue by willpaige** [nicolas-t/Chocolat#58]
Each time the lightbox is opened a new instance is created?. Seems a little overkill?

<img width="535" alt="screen shot 2017-03-22 at 20 54 16" src="https://cloud.githubusercontent.com/assets/3032885/24220348/da6de214-0f41-11e7-9f8f-c1deaa614092.png">

**Comment by nicolas-t** [comment]
Hello

How do you open it ? how do you close it ?

**Comment by nicolas-t** [comment]
indeed you're right and that's not the expected behaviour.

Will fix it.

**Comment by nicolas-t** [comment]
fixed and deployed in 0.4.17
https://github.com/nicolas-t/Chocolat/releases/tag/0.4.17

thanks again.

**Comment by willpaige** [comment]
Good stuff love the plugin!
