### ISSUE TITLE
transition on image doesn't fade on first load

### ISSUE THREAD

**Issue by willpaige** [nicolas-t/Chocolat#59]
Hi, 

Just been playing around with your plugin again and have noticed that; the first time you open the light box it appends `chocolat-wrapper`  which prevents the image from fading in. If you then close the light box and click an image again it fades in as it should. 

Possible solution would be to append the `chocolat-wrapper` on first load?

Hope this makes sense?. 

Will

**Comment by nicolas-t** [comment]
thanks again.

fixed here : 
https://github.com/nicolas-t/Chocolat/releases/tag/0.4.18

**Comment by willpaige** [comment]
Nice one!
