### ISSUE TITLE
How to use chocolat given the images option?

### ISSUE THREAD

**Issue by toni-michel** [nicolas-t/Chocolat#60]
Hi,

I have this problem http://stackoverflow.com/questions/43068122/prevent-click-for-chocolat-js-while-dragging-using-slick-js

And I thought i'll bind the events myself,

I want to pass the images option, but I don't know how to use it
http://chocolat.insipi.de/#settings
I cant find any example here...

It's allways called
$('.element').Chocolat
Shall I use it like so?
$.Chocolat({images: []}) ??

Or could I change the event that Chocolat listens?

Thanks!

**Comment by nicolas-t** [comment]
fixed on stackoverflow :  
https://stackoverflow.com/a/43092587/1609338
