### ISSUE TITLE
Moving the navigation or creating a custom one

### ISSUE THREAD

**Issue by nickmak** [nicolas-t/Chocolat#65]
I am curious, and am trying to build this out, but I need to have a custom header navigation for when the lightbox opens.

I am using your plugin to build a composition image viewer for my Web Firm to show clients what their site will look like. However, JS isn't my strongest point.

I wanna know if it's at all possible to tie in your next and prev functions to a custom appended div that I call in the chocolat-top?

**Comment by nicolas-t** [comment]
hello,

I think you can achieve what you want by moving the `left` and `right` elements into the `top` element using the `afterMarkup` hook.

```
{
    afterMarkup: function () {
        this.elems.right.appendTo(this.elems.top)
        this.elems.left.appendTo(this.elems.top)
    }
}
```

Something like this (not tested)

**Comment by nickmak** [comment]
Oh my, I tried this a couple times, and it didn't work, but the copy paste worked just fine! 

Thank you!
