### ISSUE TITLE
Owl Carousel Compatibility

### ISSUE THREAD

**Issue by enkota** [nicolas-t/Chocolat#66]
Hey!

I'm trying to get `chocolat.js` to work with `Owl Carousel`. Unfortunately, the markup used is a bit different. The issue is that there is an additional `div` before the `<a>` tag of each image. What would be the best way to approach this without re-writing the markup? Currently only the first image will work on click. Thanks!

```
<div class="chocolat-parent">

    <div class="owl-item cloned">
        <a class="chocolat-image" href="http://img.jpg">
            <img src="http://img.jpg">
        </a>
    </div>

    <div class="owl-item cloned">
        <a class="chocolat-image" href="http://img.jpg">
            <img src="http://img.jpg">
        </a>
    </div>

    <div class="owl-item cloned">
        <a class="chocolat-image" href="http://img.jpg">
            <img src="http://img.jpg">
        </a>
    </div>

</div>
```

**Comment by nicolas-t** [comment]
I'm not sure to understand, 
You want to have a carousel of clickable thumbnails, once you click one thumbnail it opens chocolat ?
Can you share your js for both chocolat and owl ?

what about :  
```html

<div class="chocolat-parent">
    <a class="owl-item cloned chocolat-image" href="http://img.jpg">
        <img src="http://img.jpg">
    </a>
    <a class="owl-item cloned chocolat-image" href="http://img.jpg">
        <img src="http://img.jpg">
    </a>
    <a class="owl-item cloned chocolat-image" href="http://img.jpg">
        <img src="http://img.jpg">
    </a>
</div>
```
maybe you'll have to add a bit of css 
```css
.owl-item {
    display:block;
}
```


As always an online demo of the issue is welcome :)

**Comment by enkota** [comment]
Hey, sorry for the delay!

Somehow it's working on a jsFiddle demo I made. I'll need to check through my code and see what's causing it!  If you open the inspector on the demo you can see OC2 is adding in a few classes to the markup via js. 

If anyone needs an example of Chocolat.js working with Owl Carousel 2 have a look [here](https://jsfiddle.net/L4q9mrh0/7/).

**Comment by nicolas-t** [comment]
Thanks !
