### ISSUE TITLE
bootstrap tooltip title conflict with chocolat

### ISSUE THREAD

**Issue by neuropass** [nicolas-t/Chocolat#69]
There is an issue with the caption taken from the title attribute when using chocolat + bootstrap framework.

Bootstrap will empty the title="" attribute and clones the content to data-original-title=""
Therefore the caption title are not displaying under chocolat.

What can be done to workaround this issue?

**Comment by nicolas-t** [comment]
Hello,

Instead on relying on the markup you can pass the chocolat `images` options, like this : 
https://github.com/nicolas-t/Chocolat/blob/master/dist/index.html#L147L151
where you can specify the title.

Or,  you can modify this line : 
https://github.com/nicolas-t/Chocolat/blob/master/src/js/jquery.chocolat.js#L31 
`title : $(this).attr('title'),` becomes `title : $(this).attr('data-original-title'),`

I think chocolat shouldn't use the title attribute anymore.  
I'll replace it with data attributes instead, that's what they're made for.

**Comment by areknow** [comment]
@nicolas-t has the following been completed? "I think chocolat shouldn't use the title attribute anymore." ?

**Comment by nicolas-t** [comment]
Hello,

It's still relying on the title attribute.
But you can use the `images`  array with version 1 like this : 
https://chocolat.gitbook.io/chocolat/usage#instanciating-using-javascript-objects

Or with legacy 0.4 like this : 
https://github.com/nicolas-t/Chocolat/blob/master/dist/index.html#L147L151
