### ISSUE TITLE
MS Internet Explorer 11 issue: full screen mode does not close

### ISSUE THREAD

**Issue by SilatPerisaiDiri** [nicolas-t/Chocolat#72]
MS Internet Explorer 11 issue:
In MS IE when the "div.chocolat-wrapper" has been set to full screen mode, attempting to close the overlay by clicking on the "X" icon or outside of the image wrapper element "div.chocolat-content", or pressing the "Esc" key has no effect.

The fix, add on line 442: 
```
else if (document.msExitFullscreen) { 
  document.msExitFullscreen();
  this.settings.fullscreenOpen = false; 
}
```

**Comment by nicolas-t** [comment]
thanks, we'll make a release with the fix in the coming hours

**Comment by nicolas-t** [comment]
there you go https://github.com/nicolas-t/Chocolat/releases/tag/0.4.19
