### ISSUE TITLE
latest jquery version

### ISSUE THREAD

**Issue by Onisho** [nicolas-t/Chocolat#75]
Can't get it to work with the latest jquery version... should it work with this version?
https://code.jquery.com/jquery-3.2.1.slim.min.js

**Comment by nicolas-t** [comment]
Hello,

chocolat uses jquery's animations, it seems that jquery removed animation from its "slim" version.
You should try with the non slim version.
Also, do you have an error message in your browser console ?

thanks

**Comment by Onisho** [comment]
Right!  Works like a charm now. Thanks a lot.  Didn't know the slim version skipped the animation.
