### ISSUE TITLE
Add hook for closing lightbox

### ISSUE THREAD

**Issue by Julime** [nicolas-t/Chocolat#76]
There is an hook for opening (`afterImageLoad`). I would like something like that for closing it.

**Comment by nicolas-t** [comment]
Hello,

You can easily create your own hooks after looking at this commit :  
https://github.com/nicolas-t/Chocolat/commit/3f479636e355ffe7118d8b9fbace8af93d92687a#diff-8ceda4c659a7857c240e1ea91a40296eL56

If you do so I'll gladly merge a pull request :) 

thanks
