### ISSUE TITLE
jQuery 3

### ISSUE THREAD

**Issue by joho1968** [nicolas-t/Chocolat#78]
Is this supposed to work with jQuery 3? I get no errors and no action :) Looking at the demo, there's "slightly" more going on than just a HTML / JS lightbox, so I'm sure I've done something wrong :)

**Comment by mattbag** [comment]
Works for me

**Comment by joho1968** [comment]
Great. Do you have a simple working example?

**Comment by ntlaseca** [comment]
I think I may be encountering a similar issue. Chocolat worked fine until I upgraded to jQuery 3. I haven't made any other changes.

**Comment by the21st** [comment]
I see there's been a commit for using jQuery 3. @nicolas-t can you please make a new release containing this change?

**Comment by mattbag** [comment]
https://codepen.io/mattbag/pen/NBgYGe

No issues with the basic, maybe some options?

**Comment by nicolas-t** [comment]
Working well for me too.
I'm creating a new release right now.

**Comment by nicolas-t** [comment]
There you go : https://github.com/nicolas-t/Chocolat/releases/tag/0.4.20

I'm closing.
If you have a reproductible issue related to jquery 3 feel free to reopen.
