### ISSUE TITLE
How to make a gallery

### ISSUE THREAD

**Issue by ametthey** [nicolas-t/Chocolat#79]
I'm looking to make a gallery with chocolate but with one clickable link to display it. Any clue ?

**Comment by mattbag** [comment]
Sure check the bottom of the doc page, there's the api and the demo.

**Comment by nicolas-t** [comment]
You'll find examples here : 
https://github.com/nicolas-t/Chocolat/blob/master/dist/index.html

(closing, feel free to reopen if needed)
