### ISSUE TITLE
Page (image) transition animation ... 

### ISSUE THREAD

**Issue by joopvos** [nicolas-t/Chocolat#81]
It would be nice if there was (also) a fading animation between page transitions ... if there is a gallery ... :)

**Comment by whatsnewsisyphus** [comment]
+1 Let me know if you need somebody to test it. Thinking of using chocolat on a major page instead of separate lightbox and sliders

**Comment by nicolas-t** [comment]
Hello,

You can try the beta version of V1 : 
https://github.com/nicolas-t/Chocolat/releases/tag/v1.0.0-beta.0
(I can publish it to npm if you use a packet manager) 

With this new version transition I handled in css.

Thanks

**Comment by whatsnewsisyphus** [comment]
Thank you Nicolas! Quick question, is there anyway to use Chocolat as a lightbox on a grid of thumbnails so that the slider is not instantiated within the normal dom, rather only in a modal/popup?

**Comment by nicolas-t** [comment]
Yep,

If I understand correctly, you juste need to call Chocolat once your modal is open.
Something like this : 
```html
<!-- Modal code -->
<div id="my-modal ">
            <a class="chocolat-image" href="1.jpg">
                <img src="thumb1.jpg">
            </a>
            <a class="chocolat-image" href="2.jpg">
                <img src="thumb2.jpg">
            </a>
            <a class="chocolat-image" href="3.jpg">
                <img src="thumb3.jpg">
            </a>
</div>
```
```js
// js code that opens the modal, and instaciante Chocolat
modal.open() //pseudo code
Chocolat(document.querySelectorAll('#my-modal .chocolat-image'))
```

**Comment by whatsnewsisyphus** [comment]
To clarify, I meant to ask, if you had the thumbnails visible on the page
already, imagine an album page, can clicking a thumbnail directly launch
chocolat in full screen mode without having the slider visible within the
scrolling page?

Best,
d

**Comment by nicolas-t** [comment]
Yes, something like this should do the work : 

```html
<div id="thumbs">
    <a class="chocolat-image" href="demo-images/5.jpg">
        <img src="demo-images/5.jpg" style="width:75px; height:50px" alt="">
    </a>
    <a class="chocolat-image" href="demo-images/6.jpg">
        <img src="demo-images/6.jpg" style="width:75px; height:50px" alt="">
    </a>
    <a class="chocolat-image" href="demo-images/3.jpg">
        <img src="demo-images/3.jpg" style="width:75px; height:50px" alt="">
    </a>
</div>
```

```js
Chocolat(document.querySelectorAll('#thumbs .chocolat-image'), {})
```

If you need more help, please open your own issue to avoid polluting this one.

Thanks,

**Comment by whatsnewsisyphus** [comment]
Wow, so sorry I was replying from email and totally forgot that this was under another issue. I usually am the one calling people to order on github! *ducks out in shame*
