### ISSUE TITLE
Have an image appear by url

### ISSUE THREAD

**Issue by tonhaarmans** [nicolas-t/Chocolat#86]
It would be handy if I could send someone a link like http://somesite.com/gallery.html#someimagetitle and this would show the image with the title 'someimagetitle'...

**Comment by nicolas-t** [comment]
Hello,

This is out of the scope of the scope of this library, but it can be achieved from outside of chocolat.

By checking if the url contains a hash (on page load)
If it does, using the api (https://github.com/nicolas-t/Chocolat/blob/master/dist/index.html#L179) you can open the right image in the slideshow

**Comment by tonhaarmans** [comment]
Yes, I got it together. If you want have a look on https://www.wideopenwindows.be/gallery.html <https://www.wideopenwindows.be/gallery.html> and https://www.wideopenwindows.be/js/setup <https://www.wideopenwindows.be/js/setup>.js

Greetings!

**Comment by nicolas-t** [comment]
cool ! 

i'm closing
