### ISSUE TITLE
Commercial Website Usage

### ISSUE THREAD

**Issue by krishnaraj** [nicolas-t/Chocolat#90]
Can you please clarify using this library on a commercial website? The license only says that open source projects can use this under GPLv3. What about commercial sites?

**Comment by nicolas-t** [comment]
Sorry for the late answer, for some reasons github is not notifying me anymore.

Feel free to use Chocolat for any commercial purpose.

**Comment by sebastian-raubach** [comment]
So you're saying it's ok to use this library for commercial purposes, but I cannot use it in an open source project that uses the Apache v2 license, because they aren't compatible?
