### ISSUE TITLE
How to reproduce styling in demo?

### ISSUE THREAD

**Issue by CptMeatball** [nicolas-t/Chocolat#91]
I was triggered by the styling in the demo, which has most information in the top bar. Is this custom styling/settings or is there some part of the docs I've failed to find?

**Comment by nicolas-t** [comment]
Hello, 

You can achieve this by modifying the markup with the hook `afterMarkup`, you'll find an example here : 
https://github.com/nicolas-t/Chocolat/issues/65#issuecomment-307143028
and in the readme : 
```js
$('#example').Chocolat({
  afterMarkup: function () {
    this.elems.description.appendTo(this.elems.top)
  }
})
```

It's a very flexible function and I can help you if you share more details about what you're trying to achieve.

You can also override the default css to make some positioning adjustments.

**Comment by CptMeatball** [comment]
Ah thanks!
